print("Welcome")
print("Hello World")
print('single quote')
print("single quote's in double quotes")
print('''printing Mulitipe lines 
      of code''')
print("inside the parenthesis () is the message it will display")
print("Make sure use quotation marks around the text messages.")
print("check on p in print it should be small")
print("Numbers don't require quotation marks")
print(30)
